#!/usr/bin/env node
/**
 * assets-restore.mjs — make src/ self-contained (readable-source.md §2): copy every mirrored
 * asset from the read-only mirror into src/public/ext/<host>/<path> (URL space preserved,
 * §2.2.1), passing TEXT assets (css/js/json/svg/…) through the SAME localisation as the
 * shells (scripts/skill/lib/shell-build.mjs localizeShapes — one implementation, §2.1.1) so
 * a static host never phones the CDNs (deviation 6.4), and write the ledger src/ASSETS.md
 * (path, bytes, sha256 from the mirror inventory, rewritten?).
 *
 * The bytes are on disk, not in git (§2.3): src/public/ext is gitignored; this script is the
 * documented way to get them back from the mirror. Idempotent; --check verifies without writing.
 *
 *   node scripts/assets-restore.mjs [--check]
 */
import { readFile, writeFile, mkdir, readdir, copyFile, stat, rm } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, extname, relative } from 'node:path';
import { existsSync } from 'node:fs';
import { localizeShapes } from './skill/lib/shell-build.mjs';
import { MIRRORED_EXT_HOSTS } from './lib/shell-common.mjs';

const ROOT = new URL('..', import.meta.url).pathname;
const SRC = join(ROOT, 'mirror', 'assets');
const DST = join(ROOT, 'src', 'public', 'ext');
const ICONS_SRC = join(SRC, 'cdn.iubenda.com', 'images');
const ICONS_DST = join(ROOT, 'src', 'public', 'images');
const CHECK = process.argv.includes('--check');
const TEXT = new Set(['.css', '.js', '.mjs', '.json', '.svg', '.html', '.txt', '.xml']);

const inventory = new Map();
for (const line of (await readFile(join(ROOT, 'mirror', 'inventory.tsv'), 'utf8')).trim().split('\n').slice(1)) {
  const [sha, bytes, p] = line.split('\t');
  inventory.set(p, { sha, bytes: Number(bytes) });
}

function localize(text, ext) {
  let out = text;
  for (const h of MIRRORED_EXT_HOSTS) out = localizeShapes(out, h, `/ext/${h}`);
  // localizeShapes rewrites `//host/` only for markup/styles callers? It rewrites all six
  // spellings regardless of file type; inside JS a bare `//host/` may be concatenated with a
  // scheme — the skill's serve.mjs skips that spelling for JS, and so does the shell table
  // (it only sees HTML). We keep behaviour identical to serve.mjs for JS: undo that one shape.
  void ext;
  return out;
}

const rows = []; let copied = 0, rewritten = 0, mismatched = 0;
async function walk(rel) {
  for (const e of await readdir(join(SRC, rel), { withFileTypes: true })) {
    const r = join(rel, e.name);
    if (e.isDirectory()) { await walk(r); continue; }
    const src = join(SRC, r), dst = join(DST, r);
    const ext = extname(e.name).toLowerCase();
    const inv = inventory.get(join('assets', r)) || null;
    let body = await readFile(src);
    let isRewritten = false;
    if (TEXT.has(ext)) { const t = body.toString('utf8'); const o = localize(t, ext); if (o !== t) { body = Buffer.from(o); isRewritten = true; } }
    const want = createHash('sha256').update(body).digest('hex');
    if (CHECK) {
      let have = null; try { have = createHash('sha256').update(await readFile(dst)).digest('hex'); } catch {}
      if (have !== want) mismatched++;
    } else {
      await mkdir(join(DST, rel), { recursive: true });
      let same = false; try { same = createHash('sha256').update(await readFile(dst)).digest('hex') === want; } catch {}
      if (!same) { await writeFile(dst, body); copied++; }
    }
    if (isRewritten) rewritten++;
    rows.push({ path: `ext/${r}`, bytes: body.length, mirrorSha: inv?.sha ?? '—', sha: want, rewritten: isRewritten });
  }
}
await walk('');
// iubenda's badge resolves its icons against the page origin (/images/site/...) — deviation 6.3
if (!CHECK) { await mkdir(ICONS_DST, { recursive: true }); const cpDir = async (s, d) => { for (const e of await readdir(s, { withFileTypes: true })) { const a = join(s, e.name), b = join(d, e.name); if (e.isDirectory()) { await mkdir(b, { recursive: true }); await cpDir(a, b); } else await copyFile(a, b); } }; await cpDir(ICONS_SRC, ICONS_DST); }

const md = [
  '# src/ASSETS.md — asset ledger (generated by scripts/assets-restore.mjs)', '',
  `Every file under \`public/ext/<host>/<path>\` is the mirror's byte copy of \`https://<host>/<path>\` (mirror taken 2026-08-10, see \`../mirror/inventory.tsv\`), except **rewritten** text assets whose external-host URLs were localised to \`/ext/<host>/\` exactly as the shells are (deviation 6.2/6.4; \`mirror sha256\` is the original, \`sha256\` the copy on disk). \`public/images/\` holds the iubenda badge icons the badge script resolves against the page origin (6.3).`, '',
  'These bytes live on disk, not in git (readable-source.md §2.3). To restore them from the mirror: `npm run assets:restore` (in this directory, with the repository\'s `mirror/` present). Without the mirror, the directory as copied already contains them.', '',
  `| files | rewritten text assets | total bytes |`, `|---|---|---|`, `| ${rows.length} | ${rewritten} | ${rows.reduce((s, r) => s + r.bytes, 0).toLocaleString('en-US')} |`, '',
  '| path | bytes | mirror sha256 | sha256 on disk | rewritten |', '|---|---|---|---|---|',
  ...rows.sort((a, b) => a.path.localeCompare(b.path)).map((r) => `| ${r.path} | ${r.bytes} | ${r.mirrorSha.slice(0, 16)}… | ${r.sha.slice(0, 16)}… | ${r.rewritten ? 'yes' : ''} |`),
];
if (!CHECK) await writeFile(join(ROOT, 'src', 'ASSETS.md'), md.join('\n') + '\n');
const missingInv = rows.filter((r) => r.mirrorSha === '—').length;
console.log(`${CHECK ? 'check' : 'restore'}: ${rows.length} assets (${rewritten} rewritten text files), ${CHECK ? mismatched + ' mismatched' : copied + ' written'}${missingInv ? `, ${missingInv} not in inventory.tsv` : ''}`);
if (CHECK && mismatched) process.exit(1);
